/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-surface-variant": "#45474c",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#3c475a",
        "on-tertiary-container": "#00a292",
        "on-background": "#0b1c30",
        "surface-container": "#e5eeff",
        "on-secondary-container": "#00714d",
        "on-tertiary-fixed-variant": "#005048",
        "background": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#8590a6",
        "inverse-primary": "#bcc7de",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4fdbc8",
        "tertiary-fixed": "#71f8e4",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#1e293b",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#6cf8bb",
        "outline-variant": "#c5c6cd",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "surface": "#f8f9ff",
        "tertiary-container": "#002f29",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#545f73",
        "on-primary-fixed": "#111c2d",
        "tertiary": "#001815",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#bcc7de",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "secondary": "#006c49",
        "primary-fixed": "#d8e3fb",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed": "#00201c",
        "primary": "#091426",
        "outline": "#75777d",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "xs": "4px",
        "lg": "24px",
        "xl": "40px",
        "xxl": "64px",
        "container-max": "1280px",
        "base": "4px",
        "gutter": "24px",
        "sm": "8px",
        "md": "16px"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "0", "fontWeight": "700"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-md": ["30px", {"lineHeight": "38px", "letterSpacing": "0", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "0", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
